### ISSUE TITLE
Patch isn't working on v1.0

### ISSUE THREAD

**Issue by zephyroths** [AdmiralCurtiss/SenPatcher#128]
With the v1.0 released I was directed to remove the old patch and reapply the patch with the newer version. But the patch doesn't seem to work, I've only tested this with CS2 though. One particular patch that I notice didn't work is the one where it should remove the animation skip in Turbo Mode. I also try to redo the process just to make sure I did it correctly and it still doesn't work. As for my system I run this game on Linux using Proton

**Comment by AdmiralCurtiss** [comment]
If you're using Proton you need to ensure that Proton loads the DLL. If you're running through Steam [use these instructions](https://github.com/AdmiralCurtiss/SenPatcher?tab=readme-ov-file#steam-deck), if you're running it directly make sure the mentioned environment variable is set before you launch the game.

If this still doesn't work, it might be misdetecing the game in memory. Does it generate a `senpatcher_inject_cs2.log` next to the executable, and if yes what does it contain?

**Comment by zephyroths** [comment]
it works, but before this version I don't even need to set the environment variable for it to work. thanks.

**Comment by AdmiralCurtiss** [comment]
Yes, because as mentioned in the release notes for v1.0, I completely reworked how the patching works. Previously the C# program would modify the `.exe` and other asset files directly, now a C++-coded `.dll` is used to handle all the patching in memory when it is loaded by the unmodified game. In the case of Proton that means you need to tell Proton to actually load that `.dll`, because Proton handles `.dll`s a bit differently than native Windows.

On the plus side, this means you don't have to muck around with the janky C#/Mono GUI stuff on Linux, you can just put the `.dll` where it needs to be and completely ignore the `SenPatcherGui.exe` part.
