### ISSUE TITLE
CS2: audio fixes breaks audio in proton

### ISSUE THREAD

**Issue by zany130** [AdmiralCurtiss/SenPatcher#89]
Thanks for the great project to fix these amazing games I know the primary intended platform for this is windows but seeing as these games run almost flawlessly (even better than on windows if you ignore this bug) I thought I should bring it to your attention at least especially with the steam deck coming and how cool it would be to play these games on it.

Patching the game with the default options, audio stops working after a while (seems random but it usually happens within two hours sometimes immediately) when playing through the proton on linux.

I posted a bug report to Valve as I initially thought this was just something that happened with proton https://github.com/ValveSoftware/Proton/issues/2134

in the last post, you can find logs that I have compressed to google drive. Don't know how helpful those would be to you.

Also if you do not have a Linux machine I would be willing to test or otherwise provide more information but I would understand if you see this as something you can't fix due to this being an issue on Linux only

**Comment by AdmiralCurtiss** [comment]
Oh that's fun. Huh, wonder why that happens, the patch is supposed to make the behavior *more* consistent, not less.

I... guess maybe the audio command ringbuffer can overflow if the audio thread doesn't get to run often enough, I ran into that during debugging when I stopped the audio thread but left the main one running, and my patch definitely does create more of those commands by pushing every music change request into it.


Can you try what happens if you leave `Replace Audio Timing Thread` on but turn off `Adjust BGM queueing logic`?

**Comment by AdmiralCurtiss** [comment]
Looking at your log, yes, I think my theory is on the mark. Note the repeated `warn:seh:OutputDebugStringA "Command buffer maxed out so refused execution of command: 63504 / 65536 bytes\n"` near the end of the log.

**Comment by zany130** [comment]
yeah, I'm testing now will get back to you in a bit.

**Comment by AdmiralCurtiss** [comment]
If my theory is correct, then this is probably fixable by waiting on the main thread for the command ringbuffer to drain instead of just skipping the commands. This potentially means the game pauses for a frame or two in those situations, but that's better than the audio breaking.

Ideally I'd like to increase the size of the ringbuffer, but that's a hardcoded literal compiled in a lot of places so it'd be difficult to determine if I actually found all the places it's used in.

**Comment by zany130** [comment]
So far no issues though again like i said this seems to happen randomly and sometimes takes a while (which of course makes this difficult to debug) but I'm post back in a few hours with an update.

**Comment by zany130** [comment]
yup audio stopped playing after a while with `Replace Audio Timing Thread` on and  `Adjust BGM queueing logic` off it seems like it lossed audio a while ago ( I left the game running for a while)

**Comment by AdmiralCurtiss** [comment]
I suspect you're right and this is indeed a game bug (well, sorta, since it apparently doesn't happen on Windows) and not a SenPatcher bug. That said, if my suspicion about what causes this is correct, this should be fixable regardless. I'm a bit busy with other stuff at the moment, so I'm not sure when I'll get to it, but I'll try to make a fix for what I think is the problem when I have the time.

**Comment by AdmiralCurtiss** [comment]
On further thought I think my theory is actually wrong -- if the problem was the sound queue filling up, it would skip new sound effects/voice lines/music changes, but the currently playing music would continue playing which, if I understand your problem description correctly, is not the case. So it's probably something different, possibly the audio thread itself dying or deadlocking.

**Comment by zany130** [comment]
Yeah the issue is after a while of playing (seems to happen more on busy scenes with alot of audio sources) the game loses all audio(voices sound eff and bgm)  this seems unrelated to senpatcher as i just tested several times now with different configurations and it happens on a clean install of the game with no patches

Meaning this is either a bug in the game that only happens when ran through proton or it's a bug in proton itself either way I think this can be closed
