### ISSUE TITLE
CS2: GOG Galaxy achievement unlocking broken in CS2 1.4.1/1.4.2 (works in 1.4)

### ISSUE THREAD

**Issue by AdmiralCurtiss** [AdmiralCurtiss/SenPatcher#92]

**Comment by AdmiralCurtiss** [comment]
Should be fixed by 3ad80125bf9d148453211a16934491422c7e217d.

This was broken because some of the function offsets were incorrect (and thus called a different function compared to 1.4), which implies they used the wrong headers when compiling? Amazing this didn't crash, really.

**Comment by Arachno67** [comment]
Hi AdmiralCurtiss!

1) When your fix is applied will an achievement like "Smells Like Team Spirit" (Use Burst in Battle 50 times) unlock if the counter already exceeds 50? For example, Burst already used 75 times, after the fix the achievement unlocks when used for the 76th time or do I have to go back to a save with less than 50 uses?

2) Do I have to undo/uninstall changes made by an older version of SenPatcher before applying the fixes of a new version?

3) I am no coder. Does "fixed in master" mean that you plan on including this fix in the (hopefully soon upcoming :) 0.8.3 release?

Thanks for your efforts!

**Comment by AdmiralCurtiss** [comment]
1: Depends on how the game coded it. But yes, I think so. Plot-based achievements probably won't unlock though unless you go back to the relevant cutscenes.
2: No, you can just install over it, newer versions of SenPatcher know what older versions changed and will work just fine.
3: Yes, 'fixed in master' means it's fixed in the codebase but is not in a release yet. It will be in the next release, whichever version that may be.

**Comment by AdmiralCurtiss** [comment]
@Arachno67 https://github.com/AdmiralCurtiss/SenPatcher/releases/tag/v0.8.3

**Comment by AdmiralCurtiss** [comment]
Regarding the last one: If you [force-enable it in the Galaxy config.json](https://docs.gog.com/gc-overlay/) it seems to work (somewhat, anyway), so I'm not entirely sure what prevents it from showing up. Maybe the main executable isn't set correctly, so it doesn't know which process is the game itself, as opposed to the launcher...?

**Comment by Arachno67** [comment]
In ToCS 1 the overlay seems to be working without issues.

For ToCS 2 _"forceEnableOverlay": true_ in GOG Galaxy's _config.json_ is required, otherwise the overlay (and thus achievement pop-ups) is disabled.

I do not like to force the overlay globally though and if fixing this kind of stuff is out of scope for the SenPatcher project, it's no big deal, just a minor issue.

A bigger deal (in my opinion at least ;) is the fact that the current Xbox controller (model 1914) is incompatible with the GOG version of ToCS 1 & 2 (I do not own 3 and 4 on PC). Model 1708, which is no longer sold by the manufacturer, works fine. Using model 1914 controls are completely garbled, would be great if you could fix this one day as we most likely won't see any official patch addressing this issue.

**Comment by AdmiralCurtiss** [comment]
It's not that it's out of scope, I just have no idea how to accomplish it. What causes the overlay to (not) appear here?

As for the Controller issue, I don't have a Xbox Series Controller so I can't exactly test this, but that seems weird to me. XInput is specifically designed to avoid those kinda issues, and if Microsoft broke XInput *a lot* more games would have issues. And I think [I can see this exact snippet for filtering out the DInput devices](https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-and-directinput) in CS2 at 0x7fb360, so I'm not really sure what's going on here.

I guess what you can test is, in the CS2 main executable (ed8_2_PC_US.exe), if you open it in a hex-editor and replace the `0f 84 21 01 00 00` at `0x3fa4a1` with just `90 90 90 90 90 90` -- this forces all controllers to be recognized as XInput -- does this change anything?

**Comment by Arachno67** [comment]
_... does this change anything?_

Yes, it does. It actually fixes the issue! All buttons are now working as expected. Rumble is working as well, albeit less intense compared to model 1708.

As far as ToCS 1 is concerned I'll gladly test if you tell me what to replace.

**Comment by AdmiralCurtiss** [comment]
Interesting! The CS1 equivalent is in `ed8.exe` at `0x53a436` -- again, `0f 84 e5 00 00 00` -> `90 90 90 90 90 90` to force all controllers to be recognized as XInput instead of DInput.
